package com.liabit.flag

object NationalFlag {
    private val mCountryList = ArrayList<Country>()

    init {
        mCountryList.add(Country("Afghanistan", "AFG", "af", "93", R.drawable.afghanistan))
        mCountryList.add(Country("South Africa", "ZAF", "za", "27", R.drawable.south_africa))
        mCountryList.add(Country("Albania", "ALB", "al", "355", R.drawable.albania))
        mCountryList.add(Country("Algeria", "DZA", "dz", "213", R.drawable.algeria))
        mCountryList.add(Country("Germany", "DEU", "de", "49", R.drawable.germany))
        mCountryList.add(Country("Andorra", "AND", "ad", "376", R.drawable.andorra))
        mCountryList.add(Country("England", "GBE", "gb", "44", R.drawable.england))
        mCountryList.add(Country("Angola", "AGO", "ao", "244", R.drawable.angola))
        mCountryList.add(Country("Anguilla", "AIA", "ai", "1264", R.drawable.anguilla))
        mCountryList.add(Country("Antigua and Barbuda", "ATG", "ag", "1268", R.drawable.antigua_and_barbuda))
        mCountryList.add(Country("Saudi Arabia", "SAU", "sa", "966", R.drawable.saudi_arabia))
        mCountryList.add(Country("Argentina", "ARG", "ar", "54", R.drawable.argentina))
        mCountryList.add(Country("Armenia", "ARM", "am", "374", R.drawable.armenia))
        mCountryList.add(Country("Aruba", "ABW", "aw", "297", R.drawable.aruba))
        mCountryList.add(Country("Australia", "AUS", "au", "61", R.drawable.australia))
        mCountryList.add(Country("Austria", "AUT", "at", "43", R.drawable.austria))
        mCountryList.add(Country("Azerbaijan", "AZE", "az", "994", R.drawable.azerbaijan))
        mCountryList.add(Country("Bahamas", "BHS", "bs", "1242", R.drawable.bahamas))
        mCountryList.add(Country("Bahrain", "BHR", "bh", "973", R.drawable.bahrain))
        mCountryList.add(Country("Bangladesh", "BGD", "bd", "880", R.drawable.bangladesh))
        mCountryList.add(Country("Barbados", "BRB", "bb", "1246", R.drawable.barbados))
        mCountryList.add(Country("Belgium", "BEL", "be", "32", R.drawable.belgium))
        mCountryList.add(Country("Belize", "BLZ", "bz", "501", R.drawable.belize))
        mCountryList.add(Country("Benin", "BEN", "bj", "229", R.drawable.benin))
        mCountryList.add(Country("Bermuda", "BMU", "bm", "1441", R.drawable.bermuda))
        mCountryList.add(Country("Bhutan", "BTN", "bt", "975", R.drawable.bhutan))
        mCountryList.add(Country("Belarus", "BLR", "by", "375", R.drawable.belarus))
        mCountryList.add(Country("Bolivia", "BOL", "bo", "591", R.drawable.bolivia))
        mCountryList.add(Country("Bosnia and Herzegovina", "BIH", "ba", "387", R.drawable.bosnia_and_herzegovina))
        mCountryList.add(Country("Botswana", "BWA", "bw", "267", R.drawable.botswana))
        mCountryList.add(Country("Brazil", "BRA", "br", "55", R.drawable.brazil))
        mCountryList.add(Country("Brunei", "BRN", "bn", "673", R.drawable.brunei))
        mCountryList.add(Country("Bulgaria", "BGR", "bg", "359", R.drawable.bulgaria))
        mCountryList.add(Country("Burkina Faso", "BFA", "bf", "226", R.drawable.burkina_faso))
        //////
        mCountryList.add(Country("Burma", "MMR", "mm", "95", R.drawable.myanmar))
        mCountryList.add(Country("Burundi", "BDI", "bi", "257", R.drawable.burundi))
        mCountryList.add(Country("Cambodia", "KHM", "kh", "855", R.drawable.cambodia))
        mCountryList.add(Country("Cameroon", "CMR", "cm", "237", R.drawable.cameroon))
        mCountryList.add(Country("Canada", "CAN", "ca", "1", R.drawable.canada))
        mCountryList.add(Country("Cape Verde", "CPV", "cv", "238", R.drawable.cape_verde))
        mCountryList.add(Country("Chile", "CHL", "cl", "56", R.drawable.chile))
        mCountryList.add(Country("China", "CHN", "cn", "86", R.drawable.china))
        mCountryList.add(Country("Cyprus", "CYP", "cy", "357", R.drawable.cyprus))
        mCountryList.add(Country("Colombia", "COL", "co", "57", R.drawable.colombia))
        mCountryList.add(Country("Comoros", "COM", "km", "269", R.drawable.comoros))
        mCountryList.add(Country("Republic of the Congo", "COG", "cg", "242", R.drawable.republic_of_the_congo))
        mCountryList.add(Country("South Korea", "KOR", "kr", "82", R.drawable.south_korea))
        mCountryList.add(Country("Costa Rica", "CRC", "cr", "506", R.drawable.costa_rica))
        mCountryList.add(Country("Ivory Coast", "CIV", "ci", "225", R.drawable.ivory_coast))
        mCountryList.add(Country("Croatia", "HRV", "hr", "385", R.drawable.croatia))
        mCountryList.add(Country("Cuba", "CUB", "cu", "53", R.drawable.cuba))
        mCountryList.add(Country("Denmark", "DNK", "dk", "45", R.drawable.denmark))
        mCountryList.add(Country("Djibouti", "DJI", "dj", "253", R.drawable.djibouti))
        mCountryList.add(Country("Dominica", "DMA", "dm", "1767", R.drawable.dominica))
        mCountryList.add(Country("Scotland", "GBS", "gb", "44", R.drawable.scotland))
        mCountryList.add(Country("Egypt", "EGY", "eg", "20", R.drawable.egypt))
        mCountryList.add(Country("United Arab Emirates", "ARE", "ae", "971", R.drawable.united_arab_emirates))
        mCountryList.add(Country("Ecuador", "ECU", "ec", "593", R.drawable.ecuador))
        mCountryList.add(Country("Eritrea", "ERI", "er", "291", R.drawable.eritrea))
        mCountryList.add(Country("Spain", "ESP", "es", "34", R.drawable.spain))
        mCountryList.add(Country("Estonia", "EST", "ee", "372", R.drawable.estonia))
        mCountryList.add(Country("Ethiopia", "ETH", "et", "251", R.drawable.ethiopia))
        mCountryList.add(Country("Finland", "FIN", "fi", "358", R.drawable.finland))
        mCountryList.add(Country("France", "FRA", "fr", "33", R.drawable.france))
        mCountryList.add(Country("Gabon", "GAB", "ga", "241", R.drawable.gabon))
        mCountryList.add(Country("Gambia", "GMB", "gm", "220", R.drawable.gambia))
        mCountryList.add(Country("Georgia", "GEO", "ge", "995", R.drawable.georgia))
        mCountryList.add(Country("Ghana", "GHA", "gh", "233", R.drawable.ghana))
        mCountryList.add(Country("Gibraltar", "GIB", "gi", "350", R.drawable.gibraltar))
        mCountryList.add(Country("Greece", "GRC", "gr", "30", R.drawable.greece))
        mCountryList.add(Country("Grenada", "GRD", "gd", "1473", R.drawable.grenada))
        mCountryList.add(Country("Greenland", "GRL", "gl", "299", R.drawable.greenland))
        mCountryList.add(Country("Guatemala", "GTM", "gt", "502", R.drawable.guatemala))
        mCountryList.add(Country("Guinea", "GIN", "gn", "224", R.drawable.guinea))
        mCountryList.add(Country("Equatorial Guinea", "GNQ", "gq", "240", R.drawable.equatorial_guinea))
        mCountryList.add(Country("Guinea-Bissau", "GNB", "gw", "245", R.drawable.guinea_bissau))
        mCountryList.add(Country("Haiti", "HTI", "ht", "509", R.drawable.haiti))
        mCountryList.add(Country("Honduras", "HND", "hn", "504", R.drawable.honduras))
        mCountryList.add(Country("Hong Kong", "HKG", "hk", "852", R.drawable.hong_kong))
        mCountryList.add(Country("Hungary", "HUN", "hu", "36", R.drawable.hungary))
        mCountryList.add(Country("Christmas Island", "CXR", "cx", "61", R.drawable.christmas_island))
        /////
        mCountryList.add(Country("Marshall Islands", "MHL", "mh", "692", R.drawable.marshall_island))
        mCountryList.add(Country("Mauritius", "MUS", "mu", "230", R.drawable.mauritius))
        mCountryList.add(Country("Solomon Islands", "SLB", "sb", "677", R.drawable.solomon_islands))
        mCountryList.add(Country("Cayman Islands", "CYM", "ky", "1345", R.drawable.cayman_islands))
        mCountryList.add(Country("Cook Islands", "COK", "ck", "682", R.drawable.cook_islands))
        mCountryList.add(Country("Falkland Islands", "FLK", "fk", "500", R.drawable.falkland_islands))
        mCountryList.add(Country("Faroe Islands", "FRO", "fo", "298", R.drawable.faroe_islands))
        mCountryList.add(Country("Fiji", "FJI", "fj", "679", R.drawable.fiji))
        //////
        mCountryList.add(Country("Mariana Island", "MNP", "mp", "1670", R.drawable.northern_marianas_islands))
        //////
        mCountryList.add(Country("Turks and Caicos Islands", "TCA", "tc", "1649", R.drawable.turks_and_caicos))
        mCountryList.add(Country("British Virgin Islands", "VGB", "vg", "1284", R.drawable.british_virgin_islands))
        mCountryList.add(Country("Virgin Islands", "VIR", "vi", "1340", R.drawable.virgin_islands))
        mCountryList.add(Country("India", "IND", "in", "91", R.drawable.india))
        mCountryList.add(Country("Indonesia", "IDN", "id", "62", R.drawable.indonesia))
        mCountryList.add(Country("Iraq", "IRQ", "iq", "964", R.drawable.iraq))
        mCountryList.add(Country("Ireland", "IRL", "ie", "353", R.drawable.ireland))
        mCountryList.add(Country("Israel", "ISR", "il", "972", R.drawable.israel))
        mCountryList.add(Country("Italy", "ITA", "it", "39", R.drawable.italy))
        mCountryList.add(Country("Jamaica", "JAM", "jm", "1876", R.drawable.jamaica))
        mCountryList.add(Country("Japan", "JPN", "jp", "81", R.drawable.japan))
        mCountryList.add(Country("Jordan", "JOR", "jo", "962", R.drawable.jordan))
        mCountryList.add(Country("Kazakhstan", "KAZ", "kz", "7", R.drawable.kazakhstan))
        mCountryList.add(Country("Kenya", "KEN", "ke", "254", R.drawable.kenya))
        mCountryList.add(Country("Kyrgyzstan", "KGZ", "kg", "996", R.drawable.kyrgyzstan))
        mCountryList.add(Country("Kosovo", "XKX", "xk", "381", R.drawable.kosovo))
        mCountryList.add(Country("Kuwait", "KWT", "kw", "965", R.drawable.kuwait))
        mCountryList.add(Country("Lesotho", "LSO", "ls", "266", R.drawable.lesotho))
        mCountryList.add(Country("Latvia", "LVA", "lv", "371", R.drawable.latvia))
        mCountryList.add(Country("Lebanon", "LBN", "lb", "961", R.drawable.lebanon))
        mCountryList.add(Country("Liberia", "LBR", "lr", "231", R.drawable.liberia))
        mCountryList.add(Country("Libya", "LBY", "ly", "218", R.drawable.libya))
        mCountryList.add(Country("Liechtenstein", "LIE", "li", "423", R.drawable.liechtenstein))
        mCountryList.add(Country("Lithuania", "LTU", "lt", "370", R.drawable.lithuania))
        mCountryList.add(Country("Luxembourg", "LUX", "lu", "352", R.drawable.luxembourg))
        //////
        mCountryList.add(Country("Macau", "MAC", "mo", "853", R.drawable.macao))
        //////
        mCountryList.add(Country("Macedonia", "MKD", "mk", "389", R.drawable.republic_of_macedonia))
        mCountryList.add(Country("Madagascar", "MDG", "mg", "261", R.drawable.madagascar))
        mCountryList.add(Country("Malaysia", "MYS", "my", "60", R.drawable.malaysia))
        mCountryList.add(Country("Malawi", "MWI", "mw", "265", R.drawable.malawi))
        mCountryList.add(Country("Maldives", "MDV", "mv", "960", R.drawable.maldives))
        mCountryList.add(Country("Mali", "MLI", "ml", "223", R.drawable.mali))
        mCountryList.add(Country("Malta", "MLT", "mt", "356", R.drawable.malta))
        mCountryList.add(Country("Morocco", "MAR", "ma", "212", R.drawable.morocco))
        mCountryList.add(Country("Martinique", "MTQ", "fr", "596", R.drawable.martinique))
        mCountryList.add(Country("Mauritania", "MRT", "mr", "222", R.drawable.mauritania))
        //////
        mCountryList.add(Country("Mayotte", "MYT", "fr", "262", R.drawable.france))
        mCountryList.add(Country("Mexico", "MEX", "mx", "52", R.drawable.mexico))
        mCountryList.add(Country("Micronesia", "FSM", "fm", "691", R.drawable.micronesia))
        mCountryList.add(Country("Monaco", "MCO", "mc", "377", R.drawable.monaco))
        mCountryList.add(Country("Mongolia", "MNG", "mn", "976", R.drawable.mongolia))
        mCountryList.add(Country("Montenegro", "MNE", "me", "382", R.drawable.montenegro))
        mCountryList.add(Country("Montserrat", "MSR", "ms", "1664", R.drawable.montserrat))
        mCountryList.add(Country("Mozambique", "MOZ", "mz", "258", R.drawable.mozambique))
        mCountryList.add(Country("Namibia", "NAM", "na", "264", R.drawable.namibia))
        mCountryList.add(Country("Nauru", "NRU", "nr", "674", R.drawable.nauru))
        mCountryList.add(Country("Nepal", "NPL", "np", "977", R.drawable.nepal))
        mCountryList.add(Country("Nicaragua", "NIC", "ni", "505", R.drawable.nicaragua))
        mCountryList.add(Country("Niger", "NER", "ne", "227", R.drawable.niger))
        mCountryList.add(Country("Nigeria", "NGA", "ng", "234", R.drawable.nigeria))
        mCountryList.add(Country("Niue", "NUI", "nu", "683", R.drawable.niue))
        mCountryList.add(Country("Norway", "NOR", "no", "47", R.drawable.norway))
        //////
        mCountryList.add(Country("New Caledonia", "NCL", "nc", "687", R.drawable.france))
        mCountryList.add(Country("New Zealand", "NZL", "nz", "64", R.drawable.new_zealand))
        mCountryList.add(Country("Oman", "OMN", "om", "968", R.drawable.oman))
        mCountryList.add(Country("Uganda", "UGA", "ug", "256", R.drawable.uganda))
        //////
        mCountryList.add(Country("Uzbekistan", "UZB", "uz", "998", R.drawable.uzbekistn))
        mCountryList.add(Country("Pakistan", "PAK", "pk", "92", R.drawable.pakistan))
        mCountryList.add(Country("Palau", "PLW", "pw", "680", R.drawable.palau))
        mCountryList.add(Country("Palestine", "PSE", "ps", "970", R.drawable.palestine))
        mCountryList.add(Country("Panama", "PAN", "pa", "507", R.drawable.panama))
        mCountryList.add(Country("Paraguay", "PRY", "py", "595", R.drawable.paraguay))
        mCountryList.add(Country("Wales", "GBW", "gb", "44", R.drawable.wales))
        mCountryList.add(Country("Netherlands", "NLD", "nl", "31", R.drawable.netherlands))
        mCountryList.add(Country("Peru", "PER", "pe", "51", R.drawable.peru))
        mCountryList.add(Country("Philippines", "PHL", "ph", "63", R.drawable.philippines))
        mCountryList.add(Country("Poland", "POL", "pl", "48", R.drawable.poland))
        mCountryList.add(Country("French Polynesia", "PYF", "fr", "689", R.drawable.french_polynesia))
        mCountryList.add(Country("Puerto Rico", "PRI", "pr", "1", R.drawable.puerto_rico))
        mCountryList.add(Country("Portugal", "PRT", "pt", "351", R.drawable.portugal))
        mCountryList.add(Country("Qatar", "QAT", "qa", "974", R.drawable.qatar))
        mCountryList.add(Country("Central African Republic", "CAF", "cf", "236", R.drawable.central_african_republic))
        mCountryList.add(Country("Moldova", "MDA", "md", "373", R.drawable.moldova))
        //////
        mCountryList.add(Country("Democratic Republic of the Congo", "COD", "cd", "243", R.drawable.democratic_republic_of_congo))
        mCountryList.add(Country("Dominican Republic", "DOM", "do", "1809", R.drawable.dominican_republic))
        mCountryList.add(Country("Iran", "IRN", "ir", "98", R.drawable.iran))
        mCountryList.add(Country("North Korea", "PRK", "kp", "850", R.drawable.north_korea))
        mCountryList.add(Country("Laos", "LAO", "la", "856", R.drawable.laos))
        mCountryList.add(Country("Czech Republic", "CZE", "cz", "420", R.drawable.czech_republic))
        mCountryList.add(Country("Romania", "ROU", "ro", "40", R.drawable.romania))
        mCountryList.add(Country("United Kingdom", "GBR", "gb", "44", R.drawable.united_kingdom))
        mCountryList.add(Country("Russia", "RUS", "ru", "7", R.drawable.russia))
        mCountryList.add(Country("Rwanda", "RWA", "rw", "250", R.drawable.rwanda))
        mCountryList.add(Country("San Marino", "SMR", "sm", "378", R.drawable.san_marino))
        mCountryList.add(Country("El Salvador", "SLV", "sv", "503", R.drawable.el_salvador))
        mCountryList.add(Country("Samoa", "WSM", "ws", "685", R.drawable.samoa))
        mCountryList.add(Country("Senegal", "SEN", "sn", "221", R.drawable.senegal))
        mCountryList.add(Country("Serbia", "SRB", "rs", "381", R.drawable.serbia))
        mCountryList.add(Country("Seychelles", "SYC", "sc", "248", R.drawable.seychelles))
        mCountryList.add(Country("Sierra Leone", "SLE", "sl", "232", R.drawable.sierra_leone))
        mCountryList.add(Country("Singapore", "SGP", "sg", "65", R.drawable.singapore))
        mCountryList.add(Country("Slovakia", "SVK", "sk", "421", R.drawable.slovakia))
        mCountryList.add(Country("Slovenia", "SVN", "si", "386", R.drawable.slovenia))
        mCountryList.add(Country("Somalia", "SOM", "so", "252", R.drawable.somalia))
        mCountryList.add(Country("Sudan", "SDN", "sd", "249", R.drawable.sudan))
        mCountryList.add(Country("Sri Lanka", "LKA", "lk", "94", R.drawable.sri_lanka))
        //////
        mCountryList.add(Country("St. Kitts and Nevis", "KNA", "kn", "1869", R.drawable.saint_kitts_and_nevis))
        //////
        mCountryList.add(Country("St. Vincent and the Grenadines", "VCT", "vc", "1784", R.drawable.st_vincent_and_the_grenadines))
        mCountryList.add(Country("Sweden", "SWE", "se", "46", R.drawable.sweden))
        mCountryList.add(Country("Switzerland", "CHE", "ch", "41", R.drawable.switzerland))
        //////
        mCountryList.add(Country("Surinam", "SUR", "sr", "597", R.drawable.suriname))
        mCountryList.add(Country("Syria", "SYR", "sy", "963", R.drawable.syria))
        //////
        mCountryList.add(Country("São Tomé and Príncipe", "STP", "st", "239", R.drawable.sao_tome_and_principe))
        mCountryList.add(Country("Tajikistan", "TJK", "tj", "992", R.drawable.tajikistan))
        mCountryList.add(Country("Taiwan", "TWN", "tw", "886", R.drawable.taiwan))
        mCountryList.add(Country("Tanzania", "TZA", "tz", "255", R.drawable.tanzania))
        //////
        mCountryList.add(Country("Tuvalu", "TUV", "tv", "688", R.drawable.tubalu))
        mCountryList.add(Country("Chad", "TCD", "td", "235", R.drawable.chad))
        //////
        mCountryList.add(Country("Diego Garcia", "IOT", "io", "246", R.drawable.british_indian_ocean_territory))
        mCountryList.add(Country("Thailand", "THA", "th", "66", R.drawable.thailand))
        mCountryList.add(Country("East Timor", "TLS", "tl", "670", R.drawable.east_timor))
        mCountryList.add(Country("Togo", "TGO", "tg", "228", R.drawable.togo))
        mCountryList.add(Country("Tonga", "TON", "to", "676", R.drawable.tonga))
        mCountryList.add(Country("Trinidad and Tobago", "TTO", "tt", "1868", R.drawable.trinidad_and_tobago))
        mCountryList.add(Country("Tunisia", "TUN", "tn", "216", R.drawable.tunisia))
        mCountryList.add(Country("Turkmenistan", "TKM", "tm", "993", R.drawable.turkmenistan))
        mCountryList.add(Country("Turkey", "TUR", "tr", "90", R.drawable.turkey))
        mCountryList.add(Country("Ukraine", "UKR", "ua", "380", R.drawable.ukraine))
        mCountryList.add(Country("United States Of America", "USA", "us", "1", R.drawable.united_states_of_america))
        mCountryList.add(Country("Uruguay", "URY", "uy", "598", R.drawable.uruguay))
        mCountryList.add(Country("Vanuatu", "VUT", "vu", "678", R.drawable.vanuatu))
        mCountryList.add(Country("Vatican City", "VAT", "va", "39", R.drawable.vatican_city))
        mCountryList.add(Country("Venezuela", "VEN", "ve", "58", R.drawable.venezuela))
        mCountryList.add(Country("Vietnam", "VNM", "vn", "84", R.drawable.vietnam))
        mCountryList.add(Country("Yemen", "YEM", "ye", "967", R.drawable.yemen))
        mCountryList.add(Country("Zambia", "ZMB", "zm", "260", R.drawable.zambia))
        mCountryList.add(Country("Zimbabwe", "ZWE", "zw", "263", R.drawable.zimbabwe))
    }

    fun getFlagResourceId(alpha2: String): Int {
        for (country in mCountryList) {
            if (country.alpha2.equals(alpha2, true) || country.alpha3.equals(alpha2, true)) {
                return country.flag
            }
        }
        return R.drawable.nono
    }

    fun getFlagResourceIdByDialingCode(dialingCode: String): Int {
        for (country in mCountryList) {
            if (country.dialingCode == dialingCode) {
                return country.flag
            }
        }
        return R.drawable.nono
    }

}